/*
 * Autogenerated file, don't edit!
 */
package main
const AppName="ext-auth-srv"
const AppVersion="0.0.17"
const AppAuthor="boris.richard.laanevali@gmail.com"
const AppLicense="MIT"
const AppRepoURL="https://github.com/cloudmore/ext-auth-srv.git"
