#define AUTOGEN_HEADER
#ifdef AUTOGEN_HEADER
/*
 * Autogenerated file, don't edit!
 */
#endif  

#define Q(x) #x
#define VAR(x) Q(x)

#define WARN(m) if err!=nil{log.Println(m,err)}
#define FATAL(m) if err!=nil{log.Fatal(m,err)}
#define PANIC(m) if err!=nil{log.Fatal(m,err)}
#define ERROR(m) if err!=nil{log.Println(m);return _,err}
